#' @title PTMDR
#' @description Plink To Multifactor Dimensionality Reduction
#' @import parallel
#' @import readr
#' @import data.table
#' @import dplyr
#' @import reshape2
#' @import ggplot2
#' @import tidyr
#' @import stringr
#' @param bfile The bfile variable is required, the user needs to define the path and name of the Plink bfile (bed, bim and fam) without the extension, the three files must be named in the same way. For example genotype.bed, genotype.bim, genotype.fam the variable bfile would be (bfile = "genotype").
#' @param epiall The epiall variable is required, the user needs to define the path and name of the epi file generated by VARI3 usually episelecrjoint.epi.cc.
#' @param snp The snp variable is required. It refers to the SNP that we want to find high order interactions and convert to MDR.
#' @param out The out variable determines the output directory where all files generated by PTMDR will be written, ptmdr.txt will be the input file to MDR analysis.
#' @param plink The plink variable is by default "plink" but it is necessary to say the path of the previously downloaded plink file if it has not been added to the system executable path.
#' @details This function has developed by Alejandro Cisterna García as part of his PhD mentored by Juan Antonio Botía Blaya.
#' Help documentation has generated by roxygen2.
#' @export

PTMDR = function( bfile,
                  epii = NULL,
                  epiall,
                  snp,
                  snplist = NULL,
                  plink = "plink",
                  out = ".",
                  bernabe = NULL
){
  system(paste0("sed -i 's/[[:space:]]\\+/ /g' ",epii,""))
  system(paste0("sed -i 's/\"//g' ",epii,""))
  system(paste0("sed -i 's/[[:space:]]\\+/ /g' ",epiall,""))
  system(paste0("sed -i 's/\"//g' ",epiall,""))

  #epiinform = read_delim("dbgap/vari3/epiinform.txt",delim = " ", col_types = "cnnncccnnnccnnccc")

  epiallr = read_delim(paste0("",epiall,""),
                       delim = " ", col_types = "ncncnn")

  # Get rid of white space at the begining and the end
  # epiinform$SNP <- str_trim(epiinform$SNP)
  # epiinform$SNP2 <- str_trim(epiinform$SNP2)
  # snpf <- filter(epiinform, epiinform$SNP == snp)



  # Filtrar el archivo epiall por el snp que buscamos
  snpf <- filter(epiallr, epiallr$SNP1 == snp)
  snpfordenado <- arrange(snpf,snpf$P)
  cromo <- unique(snpfordenado$CHR2)

  newsnp <- data.frame()
  for (ii in 1:length(cromo)) {
    snpo <- filter(snpfordenado, snpfordenado$CHR2 == cromo[ii])
    snptp <- snpo[1,]
    newsnp <- rbind(newsnp,snptp)
  }

  # All best SNP2
  finalset <- newsnp$SNP2

  if (!is.null(bernabe)){
    finalset <- as.data.frame(finalset)

    # Eliminar ultimos 4 caracteres
    episin4 <- str_sub(finalset$finalset, end=-5)

    # Sustituir un caracter por otro
    episinco <- str_replace(episin4, "_", ":")

    # Quitar los espacios
    epiespacio <- str_replace_all(episinco, fixed(" "), "")

    finalset <- epiespacio

    snpsin <- str_sub(snp, end=-5)

    # Sustituir un caracter por otro
    snppre <- str_replace(snpsin, "_", ":")

    # Quitar los espacios
    snpespacio <- str_replace_all(snppre, fixed(" "), "")

    snp <- snpespacio
    }

  write.table(c(finalset, snp),
              file = paste0("",out,"/topfmdr.set"),
              sep = " ", row.names = F, col.names = F, quote = F)

  # Extract
  system(paste0("",plink," --bfile ",bfile," --extract ",out,"/topfmdr.set  --out ",out,"/prerecodemdr --make-bed"))

  # Recode
  system(paste0("",plink," --bfile ",out,"/prerecodemdr --recodeA --out ",out,"/recodeMDR"))

  # Read recode file
  mdr = read.table(paste0("",out,"/recodeMDR.raw"), header = T )

  # Todos los snps y al final el pheno
  mdrfinal <- data.frame(mdr[,7:length(mdr)], mdr$PHENOTYPE)

  # Convertir el pheno al factor
  mdrfinal$mdr.PHENOTYPE <- as.factor(mdrfinal$mdr.PHENOTYPE)
  levels(mdrfinal$mdr.PHENOTYPE)[1] <- "0"
  levels(mdrfinal$mdr.PHENOTYPE)[2] <- "1"

  # Excribir la salida
  write.table(mdrfinal, file = paste0("",out,"/ptmdr.txt"), quote = F, row.names = F)

}
