#' @title TLTO
#' @description Two Locus To Odd
#' @import parallel
#' @import readr
#' @import data.table
#' @import dplyr
#' @import reshape2
#' @import ggplot2
#' @import tidyr
#' @param l1 The l1 variable is required, the user have to specify the SNPs position. For example, l1 = "5:141025162".
#' @param l2 The l2 variable is required, the user have to specify the SNPs position. For example, l2 = "4:90637601".
#' @param bfile The bfile variable is required, the user needs to define the path and name of the Plink bfile (bed, bim and fam) without the extension, the three files must be named in the same way. For example genotype.bed, genotype.bim, genotype.fam the variable bfile would be (bfile = "genotype").
#' @param out The out variable determines the output directory where all files generated by TLTO will be written.
#' @param plink The plink variable is by default "plink" but it is necessary to say the path of the previously downloaded plink file if it has not been added to the system executable path.
#' @param core The core variable is by default core = detectCores() -1. It refers to the number of cores used.
#' @details This function has developed by Alejandro Cisterna García as part of his PhD mentored by Juan Antonio Botía Blaya.
#' Help documentation has generated by roxygen2.
#' @export



TLTO = function(l1,
                   l2,
                   bfile,
                   out = ".",
                   core = detectCores() -1,
                   plink = "plink")
{
  # We execute twolocus command
  system(paste0("",plink," --bfile ",bfile," --out ",out,"/",l1,"vs",l2," --twolocus ",l1," ",l2," --threads ",core,""))

  # Ee split the document in two: cases and controls
  system(paste0("awk '/Cases/,/Controls/ { print }' ",out,"/",l1,"vs",l2,".twolocus > ",out,"/cases"))
  system(paste0("sed -i 's/[[:space:]]\\+/ /g' ",out,"/cases"))
  system(paste0("awk '/Controls/,/All individuals/ { print }' ",out,"/",l1,"vs",l2,".twolocus > ",out,"/controls"))
  system(paste0("sed -i 's/[[:space:]]\\+/ /g' ",out,"/controls"))

  # To automate the reading
  # Read the cases file
  all_data = readLines(paste0("",out,"/cases"))

  # In [4] we have the header
  nombres = strsplit(all_data[12], " ")[[1]]
  nombres = nombres[nombres != ""]

  # In [5] we have the fist data line
  datos1 = strsplit(all_data[13], " ")[[1]]
  datos1 = datos1[datos1 != ""]

  # In [6] we have the second data line
  datos2 = strsplit(all_data[14], " ")[[1]]
  datos2 = datos2[datos2 != ""]

  # In [7] we have the third data line
  datos3 = strsplit(all_data[15], " ")[[1]]
  datos3 = datos3[datos3 != ""]

  # In [8] we have the fourth data line
  datos4 = strsplit(all_data[16], " ")[[1]]
  datos4 = datos4[datos4 != ""]

  # In [9] we have the fifth data line
  datos5 = strsplit(all_data[17], " ")[[1]]
  datos5 = datos5[datos5 != ""]


  # Create the data frame of the two locus table (cases)
  contingencia = data.frame(datos1[3],datos1[4],datos1[5],
                            datos1[6],datos1[7], stringsAsFactors = FALSE)

  names(contingencia) = c(nombres[1],nombres[2],nombres[3],nombres[4],nombres[5])

  contingencia = rbind(contingencia, c(datos2[2] , datos2[3] ,
                                       datos2[4] , datos2[5] , datos2[6]))
  contingencia = rbind(contingencia, c(datos3[2] , datos3[3] ,
                                       datos3[4] , datos3[5] , datos3[6]))
  contingencia = rbind(contingencia, c(datos4[2] , datos4[3] ,
                                       datos4[4] , datos4[5] , datos4[6]))
  contingencia = rbind(contingencia, c(datos5[2] , datos5[3] ,
                                       datos5[4] , datos5[5] , datos5[6]))
  row.names(contingencia) = c(datos1[2], datos2[1],datos3[1], datos4[1],datos5[1])


  # Read the control file
  all_data = readLines(paste0("",out,"/controls"))

  # In [4] we have the header
  nombres = strsplit(all_data[12], " ")[[1]]
  nombres = nombres[nombres != ""]

  # In [5] we have the fist data line
  datos1 = strsplit(all_data[13], " ")[[1]]
  datos1 = datos1[datos1 != ""]

  # In [6] we have the second data line
  datos2 = strsplit(all_data[14], " ")[[1]]
  datos2 = datos2[datos2 != ""]

  # In [7] we have the third data line
  datos3 = strsplit(all_data[15], " ")[[1]]
  datos3 = datos3[datos3 != ""]

  # In [8] we have the fourth data line
  datos4 = strsplit(all_data[16], " ")[[1]]
  datos4 = datos4[datos4 != ""]

  # In [9] we have the fifth data line
  datos5 = strsplit(all_data[17], " ")[[1]]
  datos5 = datos5[datos5 != ""]


  # Create the data frame of the two locus table (controls)
  contingenciact = data.frame(datos1[3],datos1[4],datos1[5],datos1[6],datos1[7], stringsAsFactors = FALSE)
  names(contingenciact) = c(nombres[1],nombres[2],nombres[3],nombres[4],nombres[5])
  contingenciact = rbind(contingenciact, c(datos2[2] , datos2[3] , datos2[4] , datos2[5] , datos2[6]))
  contingenciact = rbind(contingenciact, c(datos3[2] , datos3[3] , datos3[4] , datos3[5] , datos3[6]))
  contingenciact = rbind(contingenciact, c(datos4[2] , datos4[3] , datos4[4] , datos4[5] , datos4[6]))
  contingenciact = rbind(contingenciact, c(datos5[2] , datos5[3] , datos5[4] , datos5[5] , datos5[6]))
  row.names(contingenciact) = c(datos1[2], datos2[1],datos3[1], datos4[1],datos5[1])

  #  Convert to matrix
  tlcasos = data.matrix(contingencia)
  tlcontroles = data.matrix(contingenciact)

  # Calculation of the ratio between cases and controls
  # when the ratio is greater than 1.0 it means that there is more frequency of the combination
  # in cases and when it is lower it means that there is more frequency in the controls.
  or = tlcasos/tlcontroles

  write.table(or, file = paste0("",out,"/twotood",l1,"vs",l2,""), sep = " ",
              row.names = T, col.names = T)

  twood = read.table(paste0("",out,"/twotood",l1,"vs",l2,""), row.names = 1)

  # Tp df
  df = as.data.frame(or, row.names = T)
  row = unlist(dimnames(or)[1])
  row.names(df) = c(row[1], row[2], row[3], row[4], row[5])

  # Remove not required rows and colums
  dfp = df[-c(4), ]
  dfp = dfp[,-4]

  # To matrix
  prueba = data.matrix(dfp)

  # To long data
  data_long = gather(dfp, condition, measurement, factor_key=TRUE)
  data_long$nombres = rep(rownames(dfp),4)
  names(data_long)[c(1,3)] = c("y", "x")


  # We make the graph to facilitate the interpretation
  pdf(paste0("",out,"/plot",l1,"vs",l2,""))
  plot (ggplot(data_long, aes(fill=x, y=measurement, x=y)) +
          geom_bar(position="dodge", stat="identity")+
          geom_text(aes(label=round(measurement, 4), fontface="bold", vjust=1), position=position_dodge(width=0.9), size=3.5) +
          geom_text(aes(y=0.3, label=x, fontface="bold"), color="white", position=position_dodge(width=0.9), angle=90, size=3) +
          theme(plot.title = element_text(face="bold",hjust = 0.5),
                legend.title=element_text(face="bold"), legend.position="bottom",
                axis.title.x = element_text(face="bold"),
                axis.text.y=element_blank(),
                axis.title.y=element_text(face="bold"), axis.ticks.x=element_blank(), axis.ticks.y=element_blank(),
                panel.background=element_blank(), panel.grid.minor=element_blank(), panel.grid.major=element_blank()) +
          ggtitle(paste0("",l1,"vs",l2,"")) +
          xlab(paste0("",l2,"")) + ylab("OR cases") + labs(fill = paste0("",l1,"")) + geom_hline(yintercept=1, linetype="dashed", color = "red"))
  dev.off()

  png(paste0("",out,"/plot",l1,"vs",l2,""))
  plot (ggplot(data_long, aes(fill=x, y=measurement, x=y)) +
          geom_bar(position="dodge", stat="identity")+
          geom_text(aes(label=round(measurement, 4), fontface="bold", vjust=1), position=position_dodge(width=0.9), size=3.5) +
          geom_text(aes(y=0.3, label=x, fontface="bold"), color="white", position=position_dodge(width=0.9), angle=90, size=3) +
          theme(plot.title = element_text(face="bold",hjust = 0.5),
                legend.title=element_text(face="bold"), legend.position="bottom",
                axis.title.x = element_text(face="bold"),
                axis.text.y=element_blank(),
                axis.title.y=element_text(face="bold"), axis.ticks.x=element_blank(), axis.ticks.y=element_blank(),
                panel.background=element_blank(), panel.grid.minor=element_blank(), panel.grid.major=element_blank()) +
          ggtitle(paste0("",l1,"vs",l2,"")) +
          xlab(paste0("",l2,"")) + ylab("OR cases") + labs(fill = paste0("",l1,"")) + geom_hline(yintercept=1, linetype="dashed", color = "red"))
  dev.off()
  return (or)
}
